#!/usr/bin/env python3
"""Compile a gettext PO domain into a PoB Lua translation table."""

from __future__ import annotations

import argparse
import ast
import sys
from pathlib import Path


def po_unquote(text: str) -> str:
    return ast.literal_eval(text)


class PoError(ValueError):
    """Raised when the PO catalog cannot be compiled deterministically."""


def parse_po(path: Path) -> dict[str, str]:
    entries: dict[str, str] = {}
    msgid: str | None = None
    msgstr: str | None = None
    active: str | None = None
    entry_start = 0

    def add_entry(done_line: int) -> None:
        if msgid is None:
            return
        if msgstr is None:
            raise PoError(f"{path}:{entry_start}: msgid has no msgstr")
        if msgid == "":
            return
        if msgid in entries:
            raise PoError(f"{path}:{entry_start}: duplicate msgid {msgid!r}")
        if msgstr:
            entries[msgid] = msgstr

    def flush() -> None:
        nonlocal msgid, msgstr, active, entry_start
        add_entry(entry_start)
        msgid = None
        msgstr = None
        active = None
        entry_start = 0

    for line_no, raw_line in enumerate(path.read_text(encoding="utf-8").splitlines(), start=1):
        line = raw_line.strip()
        if not line:
            flush()
            continue
        if line.startswith("#"):
            continue
        if line.startswith("msgid "):
            flush()
            entry_start = line_no
            msgid = po_unquote(line[6:].strip())
            active = "msgid"
            continue
        if line.startswith("msgstr "):
            if msgid is None:
                raise PoError(f"{path}:{line_no}: msgstr before msgid")
            msgstr = po_unquote(line[7:].strip())
            active = "msgstr"
            continue
        if line.startswith('"') and active == "msgid":
            msgid = (msgid or "") + po_unquote(line)
            continue
        if line.startswith('"') and active == "msgstr":
            msgstr = (msgstr or "") + po_unquote(line)
            continue
        raise PoError(f"{path}:{line_no}: unsupported PO line: {raw_line}")

    flush()
    return entries


def lua_quote(text: str) -> str:
    return '"' + text.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n") + '"'


def format_lua(entries: dict[str, str]) -> str:
    lines = [
        "-- Generated by scripts/compile-lang.py; edit locale/*.po instead.",
        "return {",
    ]
    for msgid in sorted(entries):
        lines.append(f"\t[{lua_quote(msgid)}] = {lua_quote(entries[msgid])},")
    lines.append("}")
    return "\n".join(lines) + "\n"


def write_lua(entries: dict[str, str], out_path: Path) -> None:
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(format_lua(entries), encoding="utf-8")


def check_lua(entries: dict[str, str], lua_path: Path) -> int:
    expected = format_lua(entries)
    if not lua_path.exists():
        print(f"{lua_path}: missing generated file", file=sys.stderr)
        return 1
    actual = lua_path.read_text(encoding="utf-8")
    if actual != expected:
        print(f"{lua_path}: stale generated file; run scripts/compile-lang.py", file=sys.stderr)
        return 1
    return 0


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="verify generated Lua is current without writing")
    parser.add_argument("po_file", type=Path)
    parser.add_argument("lua_file", type=Path)
    args = parser.parse_args()
    entries = parse_po(args.po_file)
    if args.check:
        return check_lua(entries, args.lua_file)
    write_lua(entries, args.lua_file)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
