#!/usr/bin/env python3
"""Extract passive tree display-name msgids for the zh_TW passive domain."""

from __future__ import annotations

import argparse
import re
from pathlib import Path


TREE_GLOB = "src/TreeData/*/tree.lua"
LUA_STRING_RE = re.compile(r"(['\"])(?:\\.|(?!\1).)*\1")
NAME_RE = re.compile(r"\bname\s*=\s*(['\"])(.*?)(?<!\\)\1")


def decode_lua_string(token: str) -> str:
    body = token[1:-1]
    out: list[str] = []
    index = 0
    while index < len(body):
        ch = body[index]
        if ch != "\\" or index + 1 >= len(body):
            out.append(ch)
            index += 1
            continue
        nxt = body[index + 1]
        if nxt == "n":
            out.append("\n")
        elif nxt == "t":
            out.append("\t")
        elif nxt == "r":
            out.append("\r")
        elif nxt in ('"', "'", "\\"):
            out.append(nxt)
        else:
            out.append(nxt)
        index += 2
    return "".join(out)


def po_quote(text: str) -> str:
    return '"' + text.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n") + '"'


def collect_passive_names(root: Path) -> set[str]:
    names: set[str] = set()
    for path in sorted(root.glob(TREE_GLOB)):
        for match in NAME_RE.finditer(path.read_text(encoding="utf-8", errors="replace")):
            value = decode_lua_string(match.group(1) + match.group(2) + match.group(1))
            if value:
                names.add(value)
    return names


def existing_msgids(path: Path) -> set[str]:
    if not path.exists():
        return set()
    msgids: set[str] = set()
    active = False
    current = ""
    for raw_line in path.read_text(encoding="utf-8").splitlines():
        line = raw_line.strip()
        if line.startswith("msgid "):
            if active and current:
                msgids.add(current)
            current = decode_lua_string(line[6:].strip())
            active = True
            continue
        if active and line.startswith('"'):
            current += decode_lua_string(line)
            continue
        if active:
            if current:
                msgids.add(current)
            current = ""
            active = False
    if active and current:
        msgids.add(current)
    return msgids


def append_missing_msgids(msgids: set[str], po_path: Path) -> int:
    existing = existing_msgids(po_path)
    missing = sorted(msgids - existing)
    if not missing:
        return 0
    lines = [po_path.read_text(encoding="utf-8").rstrip(), ""]
    for msgid in missing:
        lines.append("#. Source: scripts/extract-passive-msgids.py")
        lines.append(f"msgid {po_quote(msgid)}")
        lines.append('msgstr ""')
        lines.append("")
    po_path.write_text("\n".join(lines), encoding="utf-8")
    return len(missing)


def write_po(msgids: set[str], out_path: Path) -> int:
    lines = [
        "# Extracted passive tree display-name msgids.",
        "# Generated by scripts/extract-passive-msgids.py; translate msgstr in a separate workflow.",
        "",
        'msgid ""',
        'msgstr ""',
        '"Project-Id-Version: Path of Building PoE2 Passive translation\\n"',
        '"Content-Type: text/plain; charset=UTF-8\\n"',
        '"Content-Transfer-Encoding: 8bit\\n"',
        '"Language: zh_TW\\n"',
        "",
    ]
    for msgid in sorted(msgids):
        lines.append(f"msgid {po_quote(msgid)}")
        lines.append('msgstr ""')
        lines.append("")
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text("\n".join(lines), encoding="utf-8")
    return len(msgids)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--root", type=Path, default=Path("."))
    parser.add_argument("--output", type=Path, default=Path("work/pob/passive-msgids.po"))
    parser.add_argument("--append-missing-to", type=Path)
    args = parser.parse_args()

    root = args.root.resolve()
    msgids = collect_passive_names(root)
    output = root / args.output if not args.output.is_absolute() else args.output
    count = write_po(msgids, output)
    print(f"wrote {count} passive msgids to {output}")
    if args.append_missing_to:
        append_target = root / args.append_missing_to if not args.append_missing_to.is_absolute() else args.append_missing_to
        appended = append_missing_msgids(msgids, append_target)
        print(f"appended {appended} missing passive msgids to {append_target}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
