#!/usr/bin/env python3
"""Extract item display-name msgids for zh_TW item-domain extraction."""

from __future__ import annotations

import argparse
import re
from pathlib import Path


BASE_ITEM_RE = re.compile(r"itemBases\[\s*(?P<quote>['\"])(?P<name>(?:\\.|(?!\1).)*)\1\s*\]\s*=")
START_BLOCK_RE = re.compile(r"^\s*\[\[\s*$")


def decode_lua_string(token: str) -> str:
    body = token[1:-1]
    out: list[str] = []
    i = 0
    while i < len(body):
        ch = body[i]
        if ch != "\\" or i + 1 >= len(body):
            out.append(ch)
            i += 1
            continue
        nxt = body[i + 1]
        if nxt == "n":
            out.append("\n")
        elif nxt == "t":
            out.append("\t")
        elif nxt == "r":
            out.append("\r")
        elif nxt in ('"', "'", "\\"):
            out.append(nxt)
        else:
            out.append(nxt)
        i += 2
    return "".join(out)


def po_quote(text: str) -> str:
    return '"' + text.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n") + '"'


def collect_base_names(root: Path) -> set[str]:
    names: set[str] = set()
    for path in sorted((root / "src/Data/Bases").glob("*.lua")):
        for line in path.read_text(encoding="utf-8", errors="replace").splitlines():
            match = BASE_ITEM_RE.search(line)
            if not match:
                continue
            quote = match.group("quote")
            raw_name = f'{quote}{match.group("name")}{quote}'
            names.add(decode_lua_string(raw_name))
    return names


GENERATED_BLOCK_RE = re.compile(r"^\s*local\s+\w+\s*=\s*\{")
GENERATED_TITLE_RE = re.compile(r'^\s*"([^"]+)",?\s*$')
METADATA_PREFIXES = ("Source:", "Limited to:", "Has Alt Variant", "Radius:", "League:", "Implicits:")


def collect_generated_unique_names(root: Path) -> set[str]:
    """Extract unique titles from Generated.lua table-format items."""
    names: set[str] = set()
    path = root / "src/Data/Uniques/Special/Generated.lua"
    if not path.exists():
        return names
    lines = path.read_text(encoding="utf-8", errors="replace").splitlines()
    in_block = False
    for line in lines:
        if GENERATED_BLOCK_RE.match(line):
            in_block = True
            continue
        if in_block:
            m = GENERATED_TITLE_RE.match(line)
            if m:
                title = m.group(1)
                if not any(title.startswith(p) for p in METADATA_PREFIXES):
                    names.add(title)
                    in_block = False
            elif line.strip() == "}":
                in_block = False
    return names


def collect_unique_names(root: Path) -> set[str]:
    names: set[str] = set()
    for path in sorted(Path(root / "src/Data/Uniques").rglob("*.lua")):
        lines = path.read_text(encoding="utf-8", errors="replace").splitlines()
        for idx, line in enumerate(lines):
            if not START_BLOCK_RE.match(line):
                continue
            name_idx = idx + 1
            while name_idx < len(lines) and not lines[name_idx].strip():
                name_idx += 1
            if name_idx < len(lines):
                name = lines[name_idx].rstrip()
                if name:
                    names.add(name.strip())
    return names


def write_po(msgids: set[str], out_path: Path) -> int:
    entries = sorted(msgids)
    lines = [
        "# Extracted item-domain msgids.",
        "# Generated by scripts/extract-item-msgids.py; keep msgstr empty for extraction-only phase.",
        "# Display names only: no raw item text, parser input, or import/export payloads.",
        "",
        'msgid ""',
        'msgstr ""',
        '"Project-Id-Version: Path of Building PoE2 Item translation\\n"',
        '"Content-Type: text/plain; charset=UTF-8\\n"',
        '"Content-Transfer-Encoding: 8bit\\n"',
        '"Language: zh_TW\\n"',
        "",
    ]
    for msgid in entries:
        lines.append(f"msgid {po_quote(msgid)}")
        lines.append('msgstr ""')
        lines.append("")

    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text("\n".join(lines), encoding="utf-8")
    return len(entries)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--root", type=Path, default=Path("."))
    parser.add_argument("--output", type=Path, default=Path("locale/zh_TW/LC_MESSAGES/items.po"))
    args = parser.parse_args()

    root = args.root.resolve()
    msgids: set[str] = set()
    msgids.update(collect_base_names(root))
    msgids.update(collect_unique_names(root))
    msgids.update(collect_generated_unique_names(root))
    output = root / args.output if not args.output.is_absolute() else args.output
    count = write_po(msgids, output)
    print(f"wrote {count} item msgids to {output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
