#!/usr/bin/env python3
"""Extract skill and gem display names for the zh_TW skill domain PO catalog."""

from __future__ import annotations

import argparse
import re
from pathlib import Path


DISPLAY_NAME_RE = re.compile(r'^\s*(?P<key>name|baseTypeName)\s*=\s*(?P<value>"(?:\\.|[^"])*"|\'(?:\\.|[^\'])*\')')
SKILLS_GLOB = "src/Data/Skills/*.lua"
GEMS_FILE = "src/Data/Gems.lua"
PO_HEADER = [
    "# Skill/gem display-name catalog for zh_TW extraction.",
    "# Generated by scripts/extract-skill-msgids.py; translate msgstr in a separate workflow.",
    "# Display names only: no ids, stat ids, tags, or calculations.",
    "",
]


def decode_lua_string(token: str) -> str:
    body = token[1:-1]
    out: list[str] = []
    i = 0
    while i < len(body):
        ch = body[i]
        if ch != "\\" or i + 1 >= len(body):
            out.append(ch)
            i += 1
            continue
        nxt = body[i + 1]
        if nxt == "n":
            out.append("\n")
        elif nxt == "t":
            out.append("\t")
        elif nxt == "r":
            out.append("\r")
        elif nxt in ('"', "'", "\\"):
            out.append(nxt)
        else:
            out.append(nxt)
        i += 2
    return "".join(out)


def strip_lua_comment(line: str) -> str:
    """Drop trailing comments while respecting quoted string boundaries."""
    in_single = False
    in_double = False
    escape = False
    for i, ch in enumerate(line):
        if escape:
            escape = False
            continue
        if ch == "\\":
            if in_single or in_double:
                escape = True
            continue
        if ch == "'" and not in_double:
            in_single = not in_single
            continue
        if ch == '"' and not in_single:
            in_double = not in_double
            continue
        if not in_single and not in_double and ch == "-" and i + 1 < len(line) and line[i + 1] == "-":
            return line[:i]
    return line


def po_quote(text: str) -> str:
    return '"' + text.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n") + '"'


def collect_skill_display_names(root: Path) -> set[str]:
    names: set[str] = set()
    for path in sorted(root.glob(SKILLS_GLOB)):
        for raw_line in path.read_text(encoding="utf-8", errors="replace").splitlines():
            line = strip_lua_comment(raw_line).strip()
            if not line or line.startswith("--"):
                continue
            match = DISPLAY_NAME_RE.match(line)
            if not match:
                continue
            value = match.group("value")
            if match.group("key") not in ("name", "baseTypeName"):
                continue
            if decoded := decode_lua_string(value):
                if decoded:
                    names.add(decoded)
    return names


def collect_gem_display_names(root: Path, names: set[str]) -> None:
    gems = root / GEMS_FILE
    if not gems.exists():
        return
    for raw_line in gems.read_text(encoding="utf-8", errors="replace").splitlines():
        line = strip_lua_comment(raw_line).strip()
        if not line or line.startswith("--"):
            continue
        match = DISPLAY_NAME_RE.match(line)
        if not match:
            continue
        if match.group("key") not in ("name", "baseTypeName"):
            continue
        value = match.group("value")
        if decoded := decode_lua_string(value):
            if decoded:
                names.add(decoded)


def write_po(names: set[str], out_path: Path) -> None:
    out_path.parent.mkdir(parents=True, exist_ok=True)
    lines = PO_HEADER + [
        'msgid ""',
        'msgstr ""',
        '"Project-Id-Version: Path of Building PoE2 Skill translation\\n"',
        '"Content-Type: text/plain; charset=UTF-8\\n"',
        '"Content-Transfer-Encoding: 8bit\\n"',
        '"Language: zh_TW\\n"',
        "",
    ]
    for name in sorted(names):
        lines.append(f"msgid {po_quote(name)}")
        lines.append('msgstr ""')
        lines.append("")
    out_path.write_text("\n".join(lines), encoding="utf-8")


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--root", type=Path, default=Path("."))
    parser.add_argument("--output", type=Path, default=Path("locale/zh_TW/LC_MESSAGES/skills.po"))
    args = parser.parse_args()

    root = args.root.resolve()
    names = collect_skill_display_names(root)
    collect_gem_display_names(root, names)

    output = root / args.output if not args.output.is_absolute() else args.output
    write_po(names, output)
    print(f"wrote {len(names)} skill/gem display names to {output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
