name: Update manifest.xml
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version number to set in manifest.xml'
        required: true
        default: '0.0.0'
jobs:
  push-dev:
    runs-on: ubuntu-22.04
    steps:
            - name: Set line endings
              run: git config --global core.autocrlf true
            - name: Checkout
              uses: actions/checkout@v3
              with:
                ref: 'dev'
                fetch-depth: 0
            - name: Configure bot user
              run: |
                git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
                git config --global user.name "github-actions[bot]"
            - name: Update manifest.xml
              run: python3 update_manifest.py --quiet --in-place --set-version ${{ github.event.inputs.version }}
            - name: Create Pull Request
              uses: peter-evans/create-pull-request@v5
              with:
                  title: Update manifest.xml to ${{ github.event.inputs.version }}
                  branch: manifest-${{ github.event.inputs.version }}
                  commit-message: 'Update manifest.xml to  ${{ github.event.inputs.version }}'
